"""is_available new add to Food table

Revision ID: 5eb719c38cd7
Revises: f7ca33f820e1
Create Date: 2026-08-03 16:35:00.724674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5eb719c38cd7'
down_revision: Union[str, Sequence[str], None] = 'f7ca33f820e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('is_available', sa.Boolean(), nullable=True))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('food', 'is_available')
    # ### end Alembic commands ###
